### ISSUE TITLE
ERROR: installation of package doesn't work m1 mac book air

### ISSUE THREAD

**Issue by LucaMrini** [do-unil/mlba#1]
Error in if (cond) return(expr) : the condition has length > 1
In addition: Warning message:
In system2(R(), args, stdout = TRUE, stderr = TRUE) :
  running command ''/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/bin/R' CMD config CC 2>&1' had status 1

````r
R version 4.3.3 (2024-02-29)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.2.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Zurich
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] renv_1.0.3

loaded via a namespace (and not attached):
[1] compiler_4.3.3 tools_4.3.3

**Comment by Unco3892** [comment]
Try the [following stackoverflow answer](https://stackoverflow.com/questions/72578482/issues-installing-tidyverse-package)

**Comment by Unco3892** [comment]
I'll close (resolve) this issue as you directly told me that it's fine. Let me know in case it was not resolved.
